import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const craftworkGrotes = localFont({
  src: [
    {
      path: "./fonts/CraftworkGrotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/CraftworkGrotesk-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/CraftworkGrotesk-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/CraftworkGrotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/CraftworkGrotesk-Heavy.ttf",
      weight: "800",
      style: "normal",
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={craftworkGrotes.className}>{children}</body>
    </html>
  );
}
